Data Mining and Machine Learning Assignment 1 Part B

Q 1.1

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, plot_confusion_matrix, classification_report
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPClassifier

In [2]:
path = "D:\Semester 2\Data Mining\Assignment 1\Forest.xlsx"
raw_data = pd.read_excel(path)
print(raw_data.head())

  class  b1  b2  b3   b4  b5   b6   b7  b8  b9  ...  pred_minus_obs_H_b9  \
0    d   39  36  57   91  59  101   93  27  60  ...                -2.36   
1    h   84  30  57  112  51   98   92  26  62  ...                -2.26   
2    s   53  25  49   99  51   93   84  26  58  ...                -1.46   
3    s   59  26  49  103  47   92   82  25  56  ...                 2.68   
4    d   57  49  66  103  64  106  114  28  59  ...                -2.94   

   pred_minus_obs_S_b1  pred_minus_obs_S_b2  pred_minus_obs_S_b3  \
0               -18.41                -1.88                -6.43   
1               -16.27                -1.95                -6.25   
2               -15.92                -1.79                -4.64   
3               -13.77                -2.53                -6.34   
4               -21.74                -1.64                -4.62   

   pred_minus_obs_S_b4  pred_minus_obs_S_b5  pred_minus_obs_S_b6  \
0               -21.03                -1.60                -6.18  

In [3]:
atr = raw_data.iloc[:, 1:].values
lab = raw_data.iloc[:, 0].values
atr_train, atr_test, lab_train, lab_test = train_test_split(atr, lab, test_size=0.3, random_state=21, stratify=lab)

lab = labels = target
atr = attributes = predictions

#Normalization is generally not required for Decision Tree and MLP, but it improves training efficiency in MLP
Random_state randomizes the samples. So, for each random_state, sampling will be different, but for the same random_state, sampling will remain same for each run.

Building Decision Tree Classifier

In [4]:
dt = DecisionTreeClassifier(criterion="entropy", random_state=23, max_depth=3)
dt = dt.fit(atr_train, lab_train)

#Gini impurity and Information Gain Entropy are pretty much the same and their values can be used interchangeably.

Checking Probability and Prediction

In [5]:
dtprediction = dt.predict(atr_test)
dtprobability = dt.predict_proba(atr_test)
print("Accuracy score of our model with Decision Tree:", accuracy_score(lab_test, dtprediction))
precision = precision_score(y_true=lab_test, y_pred=dtprediction, average='micro')
print("Precision score of our model with Decision Tree :", precision)
recall = recall_score(y_true=lab_test, y_pred=dtprediction, average='micro')
print("Recall score of our model with Decision Tree :", recall)

Accuracy score of our model with Decision Tree: 0.8280254777070064
Precision score of our model with Decision Tree : 0.8280254777070064
Recall score of our model with Decision Tree : 0.8280254777070064


Generating a Text report showing the main classification metrics

In [6]:
print(classification_report(lab_test,dtprediction))

              precision    recall  f1-score   support

          d        0.90      0.75      0.82        48
          h        0.86      0.69      0.77        26
          o        0.92      0.88      0.90        25
          s        0.75      0.93      0.83        58

    accuracy                           0.83       157
   macro avg       0.86      0.81      0.83       157
weighted avg       0.84      0.83      0.83       157



Generating Confusion Matrix

In [7]:
print("Confusion Matrix is :\n", confusion_matrix(lab_test, dtprediction))

Confusion Matrix is :
 [[36  0  2 10]
 [ 0 18  0  8]
 [ 3  0 22  0]
 [ 1  3  0 54]]


Building Multi-Layer Perceptron Classifier

In [8]:
mlp = MLPClassifier(max_iter=500)
mlp.fit(atr_train, np.ravel(lab_train, order='C'))

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(100,), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=500,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

Checking Probability and Prediction

In [9]:
mlpprediction = mlp.predict(atr_test)
mlpprobability = mlp.predict_proba(atr_test)
print("Accuracy score of our model with MLP :", accuracy_score(lab_test, mlpprediction))
precision = precision_score(y_true=lab_test, y_pred=mlpprediction, average='micro')
print("Precision score of our model with MLP :", precision)
recall = recall_score(y_true=lab_test, y_pred=mlpprediction, average='micro')
print("Recall score of our model with MLP :", recall)

Accuracy score of our model with MLP : 0.8853503184713376
Precision score of our model with MLP : 0.8853503184713376
Recall score of our model with MLP : 0.8853503184713376


Generating a Text report showing the main classification metrics

In [10]:
print(classification_report(lab_test,mlpprediction))

              precision    recall  f1-score   support

          d        0.90      0.92      0.91        48
          h        0.85      0.85      0.85        26
          o        0.86      0.76      0.81        25
          s        0.90      0.93      0.92        58

    accuracy                           0.89       157
   macro avg       0.88      0.86      0.87       157
weighted avg       0.88      0.89      0.88       157



Generating Confusion Matrix

In [11]:
print("Confusion Matrix is :\n", confusion_matrix(lab_test, mlpprediction))

Confusion Matrix is :
 [[44  0  3  1]
 [ 0 22  0  4]
 [ 5  0 19  1]
 [ 0  4  0 54]]


Q 1.2

In [12]:
dtprobability = dt.predict_proba(atr_test)
mlpprobability = mlp.predict_proba(atr_test)

In [19]:
probabilities = []
for i in range(len(atr_test)):
    firstSampleProbability = probabilities[i]
prob = np.array([dtprobability[i].tolist()], [mlpprobability[i].tolist()])
df = pd.DataFrame(data=prob, index=["s", "h", "d", "o"], columns=["Decision Tree", "MLP Classifier"])
print(df)

TypeError: data type not understood